package parser.node;

import parser.Parser;
import parser.ParserVisitor;
import parser.SimpleNode;

/* Generated By:JJTree: Do not edit this line. ASPCore2Predicate_name.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ASPCore2,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASPCore2Predicate_name extends SimpleNode {
    public ASPCore2Predicate_name(int id) {
        super(id);
    }

    public ASPCore2Predicate_name(Parser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(ParserVisitor visitor, Object data) {
        System.out.println(getClass().getName() + ": " + this.value);

        return
                visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=5d1e88d66692e921c036312419e27a8e (do not edit this line) */
