package parser;

import parser.Parser;
import parser.ParserVisitor;
import parser.SimpleNode;

/* Generated By:JJTree: Do not edit this line. ASPCore2Term.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ASPCore2,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASPCore2Term extends SimpleNode {
    public ASPCore2Term(int id) {
        super(id);
    }

    public ASPCore2Term(Parser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(ParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void jjtAcceptTerm(ParserVisitor visitor, ASPCore2Atom atom) {
        //System.out.println(atom.childrenTerm);
        for (int i = 0; i < children.length; i++)
            atom.childrenTerm += 1;
    }
}
/* JavaCC - OriginalChecksum=371c5fbead969d9694e1f3df692d788e (do not edit this line) */
