/* Generated By:JJTree: Do not edit this line. ASPCore2Binop_aggregate.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ASPCore2,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASPCore2Binop_aggregate extends SimpleNode {
  public ASPCore2Binop_aggregate(int id) {
    super(id);
  }

  public ASPCore2Binop_aggregate(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4a06f35b1ad3b05e10504d1d1c2cfa3f (do not edit this line) */
