/* Generated By:JJTree: Do not edit this line. ASPCore2Naf_Classic_literal.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ASPCore2,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASPCore2Naf_Classic_literal extends SimpleNode {
  public ASPCore2Naf_Classic_literal(int id) {
    super(id);
  }

  public ASPCore2Naf_Classic_literal(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3dfedffc3548a1200aae847693562b27 (do not edit this line) */
