/* Generated By:JJTree: Do not edit this line. ASPCore2Aggregate.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ASPCore2,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASPCore2Aggregate extends SimpleNode {
  public ASPCore2Aggregate(int id) {
    super(id);
  }

  public ASPCore2Aggregate(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=85d255fd7c9a5561073843a55c820ff0 (do not edit this line) */
