/* Generated By:JJTree: Do not edit this line. ASPCore2NegativeBinop.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ASPCore2,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASPCore2NegativeBinop extends SimpleNode {
  public ASPCore2NegativeBinop(int id) {
    super(id);
  }

  public ASPCore2NegativeBinop(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=14a9312ee3efdf94afcec27311d13d81 (do not edit this line) */
