/* Generated By:JJTree: Do not edit this line. ASPCore2UnequalBuiltin_atom.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ASPCore2,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASPCore2UnequalBuiltin_atom extends SimpleNode {
  public ASPCore2UnequalBuiltin_atom(int id) {
    super(id);
  }

  public ASPCore2UnequalBuiltin_atom(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4f4a91cbaa4335f3c5cd23a1afe889be (do not edit this line) */
