/* Generated By:JJTree: Do not edit this line. ASPCore2Variable.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ASPCore2,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASPCore2Variable extends SimpleNode {
  public ASPCore2Variable(int id) {
    super(id);
  }

  public ASPCore2Variable(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=00a8b850e60b21a3f830a6e72c4b101c (do not edit this line) */
