/* Generated By:JJTree: Do not edit this line. ASPCore2Weak_Terms.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ASPCore2,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASPCore2Weak_Terms extends SimpleNode {
  public ASPCore2Weak_Terms(int id) {
    super(id);
  }

  public ASPCore2Weak_Terms(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=071501d6b88bacaebc2e6e1447802327 (do not edit this line) */
