package parser;

import parser.Parser;
import parser.ParserVisitor;
import parser.SimpleNode;

/* Generated By:JJTree: Do not edit this line. ASPCore2Naf_literal.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ASPCore2,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASPCore2Naf_literal extends SimpleNode {
    public ASPCore2Naf_literal(int id) {
        super(id);
    }

    public ASPCore2Naf_literal(Parser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(ParserVisitor visitor, Object data) {

        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=3f59afb17878003b80219d69675f81da (do not edit this line) */
