/* Generated By:JJTree: Do not edit this line. ASPCore2Weight_at_Levels.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ASPCore2,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASPCore2Weight_at_Levels extends SimpleNode {
  public ASPCore2Weight_at_Levels(int id) {
    super(id);
  }

  public ASPCore2Weight_at_Levels(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=37efd9b4b18a5df5482e1698b7434b15 (do not edit this line) */
