/* Generated By:JJTree: Do not edit this line. ASPCore2Naf_Aggregate_atom.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ASPCore2,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASPCore2Naf_Aggregate_atom extends SimpleNode {
  public ASPCore2Naf_Aggregate_atom(int id) {
    super(id);
  }

  public ASPCore2Naf_Aggregate_atom(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5100db3a73c815ae5a49fb938a4966e4 (do not edit this line) */
