package parser;

import parser.Parser;
import parser.ParserVisitor;
import parser.SimpleNode;

/* Generated By:JJTree: Do not edit this line. ASPCore2Program.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ASPCore2,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASPCore2Program extends SimpleNode {
  public ASPCore2Program(int id) {
    super(id);
  }

  public ASPCore2Program(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    //System.out.println(getClass().getName());
    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2426870ebe46f33ef572d0c80348dad9 (do not edit this line) */
