package parser;

import parser.Parser;
import parser.ParserVisitor;
import parser.SimpleNode;

/* Generated By:JJTree: Do not edit this line. ASPCore2Expression_term.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ASPCore2,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASPCore2Expression_term extends SimpleNode {
  public ASPCore2Expression_term(int id) {
    super(id);
  }

  public ASPCore2Expression_term(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
      System.out.println(value);
    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=aa03394b7c6e72fb0cb9dfc4cf658597 (do not edit this line) */
