/* Generated By:JJTree: Do not edit this line. ASPCore2prova.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ASPCore2,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public class ASPCore2Prova extends SimpleNode {
  public ASPCore2Prova(int id) {
    super(id);
  }

  public ASPCore2Prova(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e8bc85026c9a3f26a9134be08bb87283 (do not edit this line) */
