/* Generated By:JJTree: Do not edit this line. ASPCore2NegativeAggregate_atom.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ASPCore2,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASPCore2NegativeAggregate_atom extends SimpleNode {
  public ASPCore2NegativeAggregate_atom(int id) {
    super(id);
  }

  public ASPCore2NegativeAggregate_atom(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1921a2d3821485999b97c13cd44f2222 (do not edit this line) */
