/* Generated By:JJTree: Do not edit this line. ASPCore2Weak_Term.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ASPCore2,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASPCore2Weak_Term extends SimpleNode {
  public ASPCore2Weak_Term(int id) {
    super(id);
  }

  public ASPCore2Weak_Term(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0003c1a74a52502010200fb9a711bd2c (do not edit this line) */
