/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 6.0_1 */
package parser;

public interface ParserTreeConstants
{
  public int JJTPARSE_ONE_LINE = 0;
  public int JJTPROGRAM = 1;
  public int JJTRULES = 2;
  public int JJTRULE = 3;
  public int JJTHEAD = 4;
  public int JJTBODY = 5;
  public int JJTDISJUNCTION = 6;
  public int JJTCONJUNCTION = 7;
  public int JJTCHOICE_ATOM = 8;
  public int JJTCHOICE_ELEMENTS = 9;
  public int JJTCHOICE_ELEMENT = 10;
  public int JJTBINOP = 11;
  public int JJTNEGATIVEBINOP = 12;
  public int JJTARITHOP = 13;
  public int JJTNEGATIVEAGGREGATE_ATOM = 14;
  public int JJTAGGREGATE_ATOM = 15;
  public int JJTAGGREGATE_ELEMENTS = 16;
  public int JJTAGGREGATE_ELEMENT = 17;
  public int JJTAGGREGATE_FUNCTION = 18;
  public int JJTATOM = 19;
  public int JJTNEGATIVEBUILTIN_ATOM = 20;
  public int JJTBUILTIN_ATOM = 21;
  public int JJTNAF_CLASSIC_LITERAL = 22;
  public int JJTCLASSIC_LITERAL = 23;
  public int JJTNAF_LITERALS = 24;
  public int JJTNAF_LITERAL = 25;
  public int JJTTERMS = 26;
  public int JJTBASIC_TERMS = 27;
  public int JJTTERM = 28;
  public int JJTBASIC_TERM = 29;
  public int JJTGROUND_TERM = 30;
  public int JJTVARIABLE_TERM = 31;
  public int JJTFUNCTION_TERM = 32;
  public int JJTEXPRESSIONS_TERM = 33;
  public int JJTEXPRESSION_TERM = 34;
  public int JJTPREDICATE_NAME = 35;


  public String[] jjtNodeName = {
    "Parse_one_line",
    "Program",
    "Rules",
    "Rule",
    "Head",
    "Body",
    "Disjunction",
    "Conjunction",
    "Choice_atom",
    "Choice_elements",
    "Choice_element",
    "Binop",
    "NegativeBinop",
    "Arithop",
    "NegativeAggregate_atom",
    "Aggregate_atom",
    "Aggregate_elements",
    "Aggregate_element",
    "Aggregate_function",
    "Atom",
    "NegativeBuiltin_atom",
    "Builtin_atom",
    "Naf_Classic_literal",
    "Classic_literal",
    "Naf_literals",
    "Naf_literal",
    "Terms",
    "Basic_terms",
    "Term",
    "Basic_term",
    "Ground_term",
    "Variable_term",
    "Function_term",
    "Expressions_term",
    "Expression_term",
    "Predicate_name",
  };
}
/* JavaCC - OriginalChecksum=44eae8fda06bc00cf97ec41dc4f7d23b (do not edit this line) */
