/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NAF = 9;
  /** RegularExpression Id. */
  int IDLOWER = 10;
  /** RegularExpression Id. */
  int IDUPPER = 11;
  /** RegularExpression Id. */
  int STRING = 12;
  /** RegularExpression Id. */
  int NUMBER = 13;
  /** RegularExpression Id. */
  int DOT = 14;
  /** RegularExpression Id. */
  int BODY_TERM_SEPARATOR = 15;
  /** RegularExpression Id. */
  int QUERY_MARK = 16;
  /** RegularExpression Id. */
  int COLON = 17;
  /** RegularExpression Id. */
  int SEMICOLON = 18;
  /** RegularExpression Id. */
  int HEAD_SEPARATOR = 19;
  /** RegularExpression Id. */
  int CONS = 20;
  /** RegularExpression Id. */
  int WCONS = 21;
  /** RegularExpression Id. */
  int PLUS = 22;
  /** RegularExpression Id. */
  int MINUS = 23;
  /** RegularExpression Id. */
  int TIMES = 24;
  /** RegularExpression Id. */
  int DIV = 25;
  /** RegularExpression Id. */
  int PARAM_OPEN = 26;
  /** RegularExpression Id. */
  int PARAM_CLOSE = 27;
  /** RegularExpression Id. */
  int SQUARE_OPEN = 28;
  /** RegularExpression Id. */
  int SQUARE_CLOSE = 29;
  /** RegularExpression Id. */
  int CURLY_OPEN = 30;
  /** RegularExpression Id. */
  int CURLY_CLOSE = 31;
  /** RegularExpression Id. */
  int EQUAL = 32;
  /** RegularExpression Id. */
  int UNEQUAL = 33;
  /** RegularExpression Id. */
  int LESS = 34;
  /** RegularExpression Id. */
  int GREATER = 35;
  /** RegularExpression Id. */
  int LESS_OR_EQ = 36;
  /** RegularExpression Id. */
  int GREATER_OR_EQ = 37;
  /** RegularExpression Id. */
  int AGGR_COUNT = 38;
  /** RegularExpression Id. */
  int AGGR_SUM = 39;
  /** RegularExpression Id. */
  int AGGR_MAX = 40;
  /** RegularExpression Id. */
  int AGGR_MIN = 41;
  /** RegularExpression Id. */
  int UPPERLETTER = 42;
  /** RegularExpression Id. */
  int LOWERLETTER = 43;
  /** RegularExpression Id. */
  int AT = 44;
  /** RegularExpression Id. */
  int ANON_VAR = 45;
  /** RegularExpression Id. */
  int ERROR_LEXICAL = 46;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int ML_COMMENT_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "<token of kind 5>",
    "\"/%\"",
    "\"%/\"",
    "<token of kind 8>",
    "\"not\"",
    "<IDLOWER>",
    "<IDUPPER>",
    "<STRING>",
    "<NUMBER>",
    "\".\"",
    "\",\"",
    "\"?\"",
    "\":\"",
    "\";\"",
    "\"|\"",
    "\":-\"",
    "\":~\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "<UNEQUAL>",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"#count\"",
    "\"#sum\"",
    "\"#max\"",
    "\"#min\"",
    "<UPPERLETTER>",
    "<LOWERLETTER>",
    "\"@\"",
    "\"_\"",
    "<ERROR_LEXICAL>",
  };

}
