/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 6.0_1 */
package parser;

public interface ParserTreeConstants
{
  public int JJTPARSE_ONE_LINE = 0;
  public int JJTPROGRAM = 1;
  public int JJTRULES = 2;
  public int JJTRULE = 3;
  public int JJTWEIGHT_AT_LEVELS = 4;
  public int JJTWEAK_TERMS = 5;
  public int JJTWEAK_TERM = 6;
  public int JJTHEAD = 7;
  public int JJTBODY = 8;
  public int JJTDISJUNCTION = 9;
  public int JJTCONJUNCTION = 10;
  public int JJTCHOICE_ATOM = 11;
  public int JJTCHOICE_ELEMENTS = 12;
  public int JJTCHOICE_ELEMENT = 13;
  public int JJTBINOP = 14;
  public int JJTNEGATIVEBINOP = 15;
  public int JJTARITHOP = 16;
  public int JJTNEGATIVEAGGREGATE_ATOM = 17;
  public int JJTAGGREGATE_ATOM = 18;
  public int JJTAGGREGATE_ELEMENTS = 19;
  public int JJTAGGREGATE_ELEMENT = 20;
  public int JJTAGGREGATE_FUNCTION = 21;
  public int JJTATOM = 22;
  public int JJTNEGATIVEBUILTIN_ATOM = 23;
  public int JJTBUILTIN_ATOM = 24;
  public int JJTNAF_CLASSIC_LITERAL = 25;
  public int JJTCLASSIC_LITERAL = 26;
  public int JJTNAF_LITERALS = 27;
  public int JJTNAF_LITERAL = 28;
  public int JJTTERMS = 29;
  public int JJTBASIC_TERMS = 30;
  public int JJTTERM = 31;
  public int JJTBASIC_TERM = 32;
  public int JJTGROUND_TERM = 33;
  public int JJTVARIABLE_TERM = 34;
  public int JJTFUNCTION_TERM = 35;
  public int JJTEXPRESSIONS_TERM = 36;
  public int JJTEXPRESSION_TERM = 37;
  public int JJTPREDICATE_NAME = 38;


  public String[] jjtNodeName = {
    "Parse_one_line",
    "Program",
    "Rules",
    "Rule",
    "Weight_at_Levels",
    "Weak_Terms",
    "Weak_Term",
    "Head",
    "Body",
    "Disjunction",
    "Conjunction",
    "Choice_atom",
    "Choice_elements",
    "Choice_element",
    "Binop",
    "NegativeBinop",
    "Arithop",
    "NegativeAggregate_atom",
    "Aggregate_atom",
    "Aggregate_elements",
    "Aggregate_element",
    "Aggregate_function",
    "Atom",
    "NegativeBuiltin_atom",
    "Builtin_atom",
    "Naf_Classic_literal",
    "Classic_literal",
    "Naf_literals",
    "Naf_literal",
    "Terms",
    "Basic_terms",
    "Term",
    "Basic_term",
    "Ground_term",
    "Variable_term",
    "Function_term",
    "Expressions_term",
    "Expression_term",
    "Predicate_name",
  };
}
/* JavaCC - OriginalChecksum=5e94d3fb294f99afcabc659b24ebd0e3 (do not edit this line) */
