/* Generated By:JavaCC: Do not edit this line. ParserDefaultVisitor.java Version 6.0_1 */
package parser;

public class ParserDefaultVisitor implements ParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Parse_one_line node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Program node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Rules node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Rule node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Weight_at_Levels node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Weak_Terms node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Weak_Term node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Head node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Body node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Disjunction node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Conjunction node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Choice_atom node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Choice_elements node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Choice_element node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Binop node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2NegativeBinop node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Arithop node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2NegativeAggregate_atom node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Aggregate_atom node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Aggregate_elements node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Aggregate_element node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Aggregate_function node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Atom node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2NegativeBuiltin_atom node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Builtin_atom node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Naf_Classic_literal node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Classic_literal node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Naf_literals node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Naf_literal node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Terms node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Basic_terms node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Term node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Basic_term node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Ground_term node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Variable_term node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Function_term node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Expressions_term node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Expression_term node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASPCore2Predicate_name node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=1860b2fb16f094ca62ebec63e7c964a6 (do not edit this line) */
