/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NAF = 8;
  /** RegularExpression Id. */
  int IDLOWER = 9;
  /** RegularExpression Id. */
  int IDUPPER = 10;
  /** RegularExpression Id. */
  int STRING = 11;
  /** RegularExpression Id. */
  int NUMBER = 12;
  /** RegularExpression Id. */
  int DOT = 13;
  /** RegularExpression Id. */
  int BODY_TERM_SEPARATOR = 14;
  /** RegularExpression Id. */
  int QUERY_MARK = 15;
  /** RegularExpression Id. */
  int COLON = 16;
  /** RegularExpression Id. */
  int SEMICOLON = 17;
  /** RegularExpression Id. */
  int HEAD_SEPARATOR = 18;
  /** RegularExpression Id. */
  int CONS = 19;
  /** RegularExpression Id. */
  int WCONS = 20;
  /** RegularExpression Id. */
  int PLUS = 21;
  /** RegularExpression Id. */
  int MINUS = 22;
  /** RegularExpression Id. */
  int TIMES = 23;
  /** RegularExpression Id. */
  int DIV = 24;
  /** RegularExpression Id. */
  int PARAM_OPEN = 25;
  /** RegularExpression Id. */
  int PARAM_CLOSE = 26;
  /** RegularExpression Id. */
  int SQUARE_OPEN = 27;
  /** RegularExpression Id. */
  int SQUARE_CLOSE = 28;
  /** RegularExpression Id. */
  int CURLY_OPEN = 29;
  /** RegularExpression Id. */
  int CURLY_CLOSE = 30;
  /** RegularExpression Id. */
  int EQUAL = 31;
  /** RegularExpression Id. */
  int UNEQUAL = 32;
  /** RegularExpression Id. */
  int LESS = 33;
  /** RegularExpression Id. */
  int GREATER = 34;
  /** RegularExpression Id. */
  int LESS_OR_EQ = 35;
  /** RegularExpression Id. */
  int GREATER_OR_EQ = 36;
  /** RegularExpression Id. */
  int AGGR_COUNT = 37;
  /** RegularExpression Id. */
  int AGGR_SUM = 38;
  /** RegularExpression Id. */
  int AGGR_MAX = 39;
  /** RegularExpression Id. */
  int AGGR_MIN = 40;
  /** RegularExpression Id. */
  int UPPERLETTER = 41;
  /** RegularExpression Id. */
  int LOWERLETTER = 42;
  /** RegularExpression Id. */
  int AT = 43;
  /** RegularExpression Id. */
  int EOL = 44;
  /** RegularExpression Id. */
  int ANON_VAR = 45;
  /** RegularExpression Id. */
  int ERROR_LEXICAL = 46;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int ML_COMMENT_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<token of kind 4>",
    "\"/%\"",
    "\"%/\"",
    "<token of kind 7>",
    "\"not\"",
    "<IDLOWER>",
    "<IDUPPER>",
    "<STRING>",
    "<NUMBER>",
    "\".\"",
    "\",\"",
    "\"?\"",
    "\":\"",
    "\";\"",
    "\"|\"",
    "\":-\"",
    "\":~\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "<UNEQUAL>",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"#count\"",
    "\"#sum\"",
    "\"#max\"",
    "\"#min\"",
    "<UPPERLETTER>",
    "<LOWERLETTER>",
    "\"@\"",
    "\"\\n\"",
    "\"_\"",
    "<ERROR_LEXICAL>",
  };

}
