/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 6.0_1 */
package parser;

public interface ParserTreeConstants
{
  public int JJTPARSE_ONE_LINE = 0;
  public int JJTPROGRAM = 1;
  public int JJTRULES = 2;
  public int JJTRULE = 3;
  public int JJTHEAD = 4;
  public int JJTBODY = 5;
  public int JJTDISJUNCTION = 6;
  public int JJTCONJUNCTION = 7;
  public int JJTCHOICE_ATOM = 8;
  public int JJTCHOICE_ELEMENTS = 9;
  public int JJTCHOICE_ELEMENT = 10;
  public int JJTBINOP = 11;
  public int JJTARITHOP = 12;
  public int JJTNAF_AGGREGATE_ATOM = 13;
  public int JJTAGGREGATE_ATOM = 14;
  public int JJTAGGREGATE_ELEMENTS = 15;
  public int JJTAGGREGATE_ELEMENT = 16;
  public int JJTAGGREGATE_FUNCTION = 17;
  public int JJTATOM = 18;
  public int JJTUNEQUALBUILTIN_ATOM = 19;
  public int JJTBUILTIN_ATOM = 20;
  public int JJTNAF_CLASSIC_LITERAL = 21;
  public int JJTCLASSIC_LITERAL = 22;
  public int JJTNAF_LITERALS = 23;
  public int JJTNAF_LITERAL = 24;
  public int JJTTERMS = 25;
  public int JJTBASIC_TERMS = 26;
  public int JJTTERM = 27;
  public int JJTBASIC_TERM = 28;
  public int JJTGROUND_TERM = 29;
  public int JJTVARIABLE_TERM = 30;
  public int JJTFUNCTION_TERM = 31;
  public int JJTEXPRESSIONS_TERM = 32;
  public int JJTEXPRESSION_TERM = 33;
  public int JJTPREDICATE_NAME = 34;


  public String[] jjtNodeName = {
    "Parse_one_line",
    "Program",
    "Rules",
    "Rule",
    "Head",
    "Body",
    "Disjunction",
    "Conjunction",
    "Choice_atom",
    "Choice_elements",
    "Choice_element",
    "Binop",
    "Arithop",
    "Naf_Aggregate_atom",
    "Aggregate_atom",
    "Aggregate_elements",
    "Aggregate_element",
    "Aggregate_function",
    "Atom",
    "UnequalBuiltin_atom",
    "Builtin_atom",
    "Naf_Classic_literal",
    "Classic_literal",
    "Naf_literals",
    "Naf_literal",
    "Terms",
    "Basic_terms",
    "Term",
    "Basic_term",
    "Ground_term",
    "Variable_term",
    "Function_term",
    "Expressions_term",
    "Expression_term",
    "Predicate_name",
  };
}
/* JavaCC - OriginalChecksum=2988566b0b74bf9bcf92b617b72bd5d4 (do not edit this line) */
