/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 6.0_1 */
public interface ParserTreeConstants
{
  public int JJTPARSEONELINE = 0;
  public int JJTPROGRAM = 1;
  public int JJTRULES = 2;
  public int JJTRULE = 3;
  public int JJTHEAD = 4;
  public int JJTBODY = 5;
  public int JJTDISJUNCTION = 6;
  public int JJTCONJUNCTION = 7;
  public int JJTCHOICE_ATOM = 8;
  public int JJTCHOICE_ELEMENTS = 9;
  public int JJTCHOICE_ELEMENT = 10;
  public int JJTBINOP = 11;
  public int JJTARITHOP = 12;
  public int JJTAGGREGATE_ATOM = 13;
  public int JJTAGGREGATE_ELEMENTS = 14;
  public int JJTAGGREGATE_ELEMENT = 15;
  public int JJTAGGREGATE_FUNCTION = 16;
  public int JJTATOM = 17;
  public int JJTBUILTIN_ATOM = 18;
  public int JJTCLASSIC_LITERAL = 19;
  public int JJTNAF_LITERALS = 20;
  public int JJTNAF_LITERAL = 21;
  public int JJTTERMS = 22;
  public int JJTBASIC_TERMS = 23;
  public int JJTTERM = 24;
  public int JJTBASIC_TERM = 25;
  public int JJTGROUND_TERM = 26;
  public int JJTVARIABLE_TERM = 27;
  public int JJTFUNCTION_TERM = 28;
  public int JJTEXPRESSIONS_TERM = 29;
  public int JJTEXPRESSION_TERM = 30;
  public int JJTPREDICATE_NAME = 31;


  public String[] jjtNodeName = {
    "parseOneLine",
    "program",
    "rules",
    "RULE",
    "HEAD",
    "BODY",
    "DISJUNCTION",
    "CONJUNCTION",
    "CHOICE_ATOM",
    "CHOICE_ELEMENTS",
    "CHOICE_ELEMENT",
    "BINOP",
    "ARITHOP",
    "AGGREGATE_ATOM",
    "AGGREGATE_ELEMENTS",
    "AGGREGATE_ELEMENT",
    "AGGREGATE_FUNCTION",
    "ATOM",
    "BUILTIN_ATOM",
    "CLASSIC_LITERAL",
    "NAF_LITERALS",
    "NAF_LITERAL",
    "TERMS",
    "BASIC_TERMS",
    "TERM",
    "BASIC_TERM",
    "GROUND_TERM",
    "VARIABLE_TERM",
    "FUNCTION_TERM",
    "EXPRESSIONS_TERM",
    "EXPRESSION_TERM",
    "PREDICATE_NAME",
  };
}
/* JavaCC - OriginalChecksum=2bb251e367754cac9fcf6678e348a07f (do not edit this line) */
